import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

const STATUS_APROVADOS = new Set(['APROVADO','APROVADO_COORD','APROVADO_ADMIN','PAGO']);
const STATUS_PENDENTES = new Set(['ENVIADO_APROVACAO','AGUARDANDO_REVISAO']);
function normalizar(v:any){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/\s+/g,' ')}
function digitos(v:any){return String(v||'').replace(/\D/g,'')}
function valor(v:any){const n=Number(v||0);return Number.isFinite(n)?n:0}
function dataRegistro(r:any){return String(r.updated_date||r.created_date||'')}
function d(r:any){return r.data||r}
function ia(r:any){return d(r).resultado_ia||r.resultado_ia||{}}
function xmlUrl(r:any){return d(r).nf_xml_url||r.nf_xml_url||ia(r).drive_xml_url||ia(r).arquivos_fiscais?.xml||''}
function pdfUrl(r:any){return d(r).arquivo_original_url||r.arquivo_original_url||ia(r).drive_pdf_url||ia(r).arquivos_fiscais?.pdf||''}
function chaveFiscal(r:any){const x=d(r),y=ia(r);const chave=digitos(x.nf_chave_acesso||x.chave_acesso||r.nf_chave_acesso||y.nf_chave_acesso);if(chave.length===44)return`chave:${chave}`;const cnpj=digitos(x.nf_emitente_cpf_cnpj||x.fornecedor_cpf_cnpj||x.cnpj_fornecedor||r.fornecedor_cpf_cnpj||y.nf_emitente_cpf_cnpj);const nf=digitos(x.nf_numero||x.numero_nota||x.numero_nf||r.nf_numero||y.nf_numero);const val=valor(x.nf_valor_total||x.valor_total||x.valor||r.nf_valor_total||y.nf_valor_total).toFixed(2);const nome=normalizar(x.nf_emitente_nome||x.fornecedor_nome||r.fornecedor_nome||y.nf_emitente_nome);if(cnpj&&nf)return`cnpj-nf:${cnpj}:${nf}`;if(nf&&val!=='0.00')return`nf-valor:${nf}:${val}:${nome}`;const arquivo=normalizar(x.file_name_final||x.file_name_original||r.file_name_final||r.file_name_original).replace(/\.(pdf|xml)$/,'').replace(/\b(comp|comprovante|xml|pdf)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();return arquivo?`arquivo:${arquivo}`:`id:${r.id}`}
function ehNotaFiscal(r:any){const x=d(r),y=ia(r);const nome=normalizar(x.file_name_final||x.file_name_original||r.file_name_final||r.file_name_original);const tipo=normalizar(x.tipo_detectado||r.tipo_detectado||y.tipo_documento);const naoFiscal=['extrato','rendimento','comprovante','recibo','devolucao','estorno','orcamento','contrato','aditivo','icon.png','image.png','bandeirola','cartaz','instagram','cracha','rider','foto','jpg','jpeg','docx'].some(t=>nome.includes(t));if(naoFiscal)return false;const temDados=Boolean(digitos(x.nf_numero||x.numero_nota||r.nf_numero||y.nf_numero)||digitos(x.nf_chave_acesso||r.nf_chave_acesso||y.nf_chave_acesso).length===44);return tipo.includes('nota_fiscal')||tipo.includes('nf')||temDados||/\bnf\b/.test(nome)}
function statusPR(pr:any){return normalizar(pr.status).toUpperCase().replace(/ /g,'_')}

Deno.serve(async(req)=>{try{const base44=createClientFromRequest(req);const user=await base44.auth.me().catch(()=>null);if(!user)return Response.json({success:false,error:'Unauthorized'},{status:401});if(!['admin','coordenador','coordinator'].includes(normalizar(user.role)))return Response.json({success:false,error:'Apenas administradores ou coordenadores.'},{status:403});
const intakes=await base44.asServiceRole.entities.DocumentIntake.list('-created_date',5000);const prs=await base44.asServiceRole.entities.PurchaseRequest.list('-created_date',5000);const aprovadasPR=new Set(prs.filter((p:any)=>STATUS_APROVADOS.has(statusPR(p))).map(chaveFiscal));const grupos=new Map<string,any[]>();const arquivados:any[]=[],consolidados:any[]=[],erros:any[]=[];
for(const intake of intakes){const status=String(intake.status_processamento||'').toUpperCase();if(STATUS_PENDENTES.has(status)&&!ehNotaFiscal(intake)){try{await base44.asServiceRole.entities.DocumentIntake.update(intake.id,{status_processamento:'NAO_FISCAL_ARQUIVADO',resultado_ia:{...(intake.resultado_ia||{}),motivo_arquivamento:'Documento não fiscal: comprovante, extrato, devolução, contrato, orçamento ou imagem',arquivado_em:new Date().toISOString()}});arquivados.push({id:intake.id,motivo:'não fiscal'})}catch(e:any){erros.push({id:intake.id,erro:String(e?.message||e)})}continue}if(ehNotaFiscal(intake)){const key=chaveFiscal(intake);if(!grupos.has(key))grupos.set(key,[]);grupos.get(key).push(intake)}}
for(const [key,items] of grupos){items.sort((a,b)=>{const sa=STATUS_APROVADOS.has(String(a.status_processamento||'').toUpperCase())?100:0,sb=STATUS_APROVADOS.has(String(b.status_processamento||'').toUpperCase())?100:0,ca=(pdfUrl(a)?10:0)+(xmlUrl(a)?5:0),cb=(pdfUrl(b)?10:0)+(xmlUrl(b)?5:0);return(sb+cb)-(sa+ca)||dataRegistro(b).localeCompare(dataRegistro(a))});const canonical=items[0];const aprovado=items.some(i=>STATUS_APROVADOS.has(String(i.status_processamento||'').toUpperCase()))||aprovadasPR.has(key);const mergedPdf=items.map(pdfUrl).find(Boolean)||'',mergedXml=items.map(xmlUrl).find(Boolean)||'';const ids=Array.from(new Set(items.flatMap(i=>[ia(i).drive_file_id,...(ia(i).drive_file_ids||[])]).filter(Boolean)));try{await base44.asServiceRole.entities.DocumentIntake.update(canonical.id,{arquivo_original_url:mergedPdf||mergedXml,nf_xml_url:mergedXml||canonical.nf_xml_url||'',resultado_ia:{...(canonical.resultado_ia||{}),drive_file_ids:ids,drive_pdf_url:mergedPdf||null,drive_xml_url:mergedXml||null,pdf_xml_unidos:Boolean(mergedPdf&&mergedXml),chave_fiscal_deterministica:key,duplicidades_consolidadas:Math.max(0,items.length-1)}});consolidados.push({id:canonical.id,chave:key,quantidade:items.length,com_xml:Boolean(mergedXml),aprovado});for(const extra of items.slice(1)){const status=String(extra.status_processamento||'').toUpperCase();if(STATUS_PENDENTES.has(status)||status===''){await base44.asServiceRole.entities.DocumentIntake.update(extra.id,{status_processamento:aprovado?'JA_APROVADO_ARQUIVADO':'DUPLICADO_ARQUIVADO',resultado_ia:{...(extra.resultado_ia||{}),duplicado_de:canonical.id,chave_fiscal_deterministica:key,arquivado_em:new Date().toISOString()}});arquivados.push({id:extra.id,duplicado_de:canonical.id,chave:key,motivo:aprovado?'já aprovado':'duplicado'})}}if(aprovado&&STATUS_PENDENTES.has(String(canonical.status_processamento||'').toUpperCase())){await base44.asServiceRole.entities.DocumentIntake.update(canonical.id,{status_processamento:'JA_APROVADO_ARQUIVADO'});arquivados.push({id:canonical.id,chave:key,motivo:'já aprovado'})}else if(!aprovado&&String(canonical.status_processamento||'').toUpperCase()==='AGUARDANDO_REVISAO'){await base44.asServiceRole.entities.DocumentIntake.update(canonical.id,{status_processamento:'ENVIADO_APROVACAO'})}}catch(e:any){erros.push({chave:key,erro:String(e?.message||e)})}}
return Response.json({success:true,resumo:{intakes_analisados:intakes.length,grupos_fiscais:grupos.size,registros_arquivados:arquivados.length,duplicados_arquivados:arquivados.filter(i=>i.motivo==='duplicado').length,ja_aprovados_retirados:arquivados.filter(i=>i.motivo==='já aprovado').length,nao_fiscais_retirados:arquivados.filter(i=>i.motivo==='não fiscal').length,grupos_consolidados:consolidados.filter(i=>i.quantidade>1).length,erros:erros.length},arquivados,consolidados,erros})}catch(e:any){return Response.json({success:false,error:String(e?.message||e)},{status:500})}});
