import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

const DRIVE_FOLDER_ID='1sI_XEZpUo3W5gcs2Nik3rGm1v6bAbKTh';
function norm(v:any){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/\s+/g,' ')}
function digits(v:any){return String(v||'').replace(/\D/g,'')}
function number(v:any){const t=String(v||'').trim();const n=Number(t.includes(',')?t.replace(/\./g,'').replace(',','.'):t);return Number.isFinite(n)?n:0}
function xmlUrl(r:any){const d=r.data||r,ia=d.resultado_ia||r.resultado_ia||{};return d.nf_xml_url||r.nf_xml_url||ia.drive_xml_url||ia.arquivos_fiscais?.xml||''}
function key(r:any){const d=r.data||r,ia=d.resultado_ia||r.resultado_ia||{};const chave=digits(d.nf_chave_acesso||r.nf_chave_acesso||ia.nf_chave_acesso);if(chave.length===44)return`chave:${chave}`;const cnpj=digits(d.nf_emitente_cpf_cnpj||d.fornecedor_cpf_cnpj||r.fornecedor_cpf_cnpj||ia.nf_emitente_cpf_cnpj);const nf=digits(d.nf_numero||r.nf_numero||ia.nf_numero);const val=number(d.nf_valor_total||r.nf_valor_total||ia.nf_valor_total).toFixed(2);if(cnpj&&nf)return`cnpj-nf:${cnpj}:${nf}`;if(nf&&val!=='0.00')return`nf-valor:${nf}:${val}`;return null}
function parseXml(text:string){const get=(ps:RegExp[])=>{for(const p of ps){const m=text.match(p);if(m?.[1])return m[1].trim()}return''};const cnpj=get([/<CNPJ[^>]*>(\d+)<\/CNPJ>/i,/<cnpj[^>]*>(\d+)<\/cnpj>/i]);const nf=get([/<nNF[^>]*>(\d+)<\/nNF>/i,/<nNfse[^>]*>(\d+)<\/nNfse>/i,/<Numero[^>]*>(\d+)<\/Numero>/i]);const val=get([/<vNF[^>]*>([\d.,]+)<\/vNF>/i,/<vLiquidoNfse[^>]*>([\d.,]+)<\/vLiquidoNfse>/i,/<ValorLiquidoNfse[^>]*>([\d.,]+)<\/ValorLiquidoNfse>/i]);const chave=get([/<chNFe[^>]*>(\d{44})<\/chNFe>/i,/<ChaveAcesso[^>]*>(\d{44})<\/ChaveAcesso>/i])||(text.match(/\b\d{44}\b/)||[])[0]||'';return{nf_emitente_cpf_cnpj:digits(cnpj),nf_numero:digits(nf),nf_valor_total:number(val),nf_chave_acesso:digits(chave)}}
function isXml(f:any){return ['text/xml','application/xml'].includes(f.mimeType)||String(f.name||'').toLowerCase().endsWith('.xml')}

Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req);const user=await base44.auth.me().catch(()=>null);if(!user)return Response.json({success:false,error:'Unauthorized'},{status:401});if(!['admin','coordenador','coordinator'].includes(norm(user.role)))return Response.json({success:false,error:'Apenas administradores ou coordenadores.'},{status:403});
 let token=null;try{token=(await base44.asServiceRole.connectors.getConnection('googledrive'))?.accessToken||null}catch(_){}if(!token)return Response.json({success:false,error:'Google Drive não conectado.'},{status:401});
 async function list(id:string){const out:any[]=[];let page='';do{const q=encodeURIComponent(`'${id}' in parents and trashed=false`);const fields=encodeURIComponent('nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink)');const r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${q}&fields=${fields}&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true${page?`&pageToken=${page}`:''}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Drive HTTP ${r.status}`);const d=await r.json();out.push(...(d.files||[]));page=d.nextPageToken||''}while(page);return out}
 async function collect(id:string,depth=0):Promise<any[]>{const items=await list(id);const xmls=items.filter(isXml);if(depth<4)for(const folder of items.filter((i:any)=>i.mimeType==='application/vnd.google-apps.folder'))xmls.push(...await collect(folder.id,depth+1));return xmls}
 async function download(f:any){const r=await fetch(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media&supportsAllDrives=true`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Download HTTP ${r.status}`);return await r.arrayBuffer()}
 const pendentes=await base44.asServiceRole.entities.DocumentIntake.filter({status_processamento:'ENVIADO_APROVACAO'},'-created_date',3000);const faltantes=pendentes.filter((i:any)=>!xmlUrl(i));const porKey=new Map<string,any>();faltantes.forEach((i:any)=>{const k=key(i);if(k&&!porKey.has(k))porKey.set(k,i)});
 const xmls=await collect(DRIVE_FOLDER_ID);const vinculados:any[]=[];const ignorados:any[]=[];const erros:any[]=[];const usados=new Set<string>();
 for(const f of xmls){try{const bytes=await download(f);const parsed=parseXml(new TextDecoder('utf-8').decode(bytes));const k=key(parsed);const intake=k?porKey.get(k):null;if(!intake||usados.has(intake.id)){ignorados.push({arquivo:f.name,motivo:intake?'nota já recebeu XML':'sem NF pendente correspondente'});continue}const file=new File([bytes],f.name,{type:f.mimeType||'application/xml'});const up=await base44.asServiceRole.integrations.Core.UploadFile({file});const url=up?.file_url||up?.url||up?.data?.file_url;if(!url)throw new Error('Upload sem URL');const ia=intake.resultado_ia||{};await base44.asServiceRole.entities.DocumentIntake.update(intake.id,{nf_xml_url:url,nf_chave_acesso:parsed.nf_chave_acesso||intake.nf_chave_acesso||'',resultado_ia:{...ia,...parsed,drive_xml_file_id:f.id,drive_xml_url:url,drive_file_ids:Array.from(new Set([...(ia.drive_file_ids||[]),f.id])),pdf_xml_unidos:Boolean(ia.drive_pdf_url||intake.arquivo_original_url),chave_fiscal_deterministica:k}});usados.add(intake.id);vinculados.push({intake_id:intake.id,arquivo:f.name,chave:k})}catch(e:any){erros.push({arquivo:f.name,erro:String(e?.message||e)})}}
 return Response.json({success:true,resumo:{notas_sem_xml:faltantes.length,xmls_encontrados:xmls.length,xmls_vinculados:vinculados.length,ignorados:ignorados.length,erros:erros.length},vinculados,ignorados,erros});
}catch(e:any){return Response.json({success:false,error:String(e?.message||e)},{status:500})}});
